site_name: avalanche-cli
site_description: |
  Avalanche-CLI is a command-line interface for building, deploying, and maintaining Avalanche
  Subnets. It can be used to prototype and test Subnets, as well as to deploy them to the
  Avalanche network. Avalanche-CLI is available for Linux and Mac, and is open source and
  available on GitHub.
nav:
  - Introduction: index.md
plugins:
  - techdocs-core
