---
- hosts: all
  tasks:
    - name: check if node is synced to subnet
      uri:
        url: http://127.0.0.1:9650/ext/bc/P
        method: POST
        body: "{\"jsonrpc\":\"2.0\", \"id\":1,\"method\" :\"platform.getBlockchainStatus\", \"params\": {\"blockchainID\":\"{{ blockchainID }}\"}}"
        body_format: json
        return_content: yes
        headers:
          Content-Type: "application/json"
      register: command_output
    - copy:
        dest: "{{ subnetSyncPath }}"
        content: "{{ command_output[\"content\"] | from_json | to_nice_json }}"
      delegate_to: localhost
