name: Lint + Unit Tests
on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: "1.17"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: .
          args: --timeout 1m
  test:
    name: Golang Unit Tests v${{ env.GO_VERSION }} (ubuntu-20.04)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go mod download
      - run: go build -v ./...
      - run: go test -v -coverprofile=coverage.out ./...
      - run: go tool cover -func=coverage.out
